name: flutter_map_marker_cluster
description: A Dart implementation of Leaflet.makercluster for Flutter apps.
  Provides beautiful animated marker clustering functionality for flutter_map.
version: 1.0.2

homepage: https://github.com/lpongetti/flutter_map_marker_cluster

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_map_marker_popup: ^4.0.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
